development: &default
  adapter: sqlite3
  database: db/redmine_development.sqlite3
  pool: 10
  timeout: 5000

test:
  <<: *default
  database: db/redmine_test.sqlite3

production:
  <<: *default
  database: db/redmine_production.sqlite3
